# Deals Part 4

Importing all necessary background stuff in order to get sql magic to work. Connecting to server

In [1]:
import pandas as pd

# Needed for %sql Magic
%load_ext sql

%sql mysql+pymysql://root:mysql@localhost/deals

C:\Users\conor\Anaconda3\lib\site-packages\pymysql\cursors.py:166: Warning: (1287, "'@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead")
  result = self._query(query)

'Connected: root@deals'

Calling the first view using sql Magic

Creating a view that shows #parts and dollar value with each deal

In [2]:
%%sql 

SELECT *
FROM dealsvalues

SyntaxError: invalid syntax (<ipython-input-2-e852b7c9bfc8>, line 2)

Calling the 5 views from the deals database

Creating a deals summary view

In [8]:

%%sql 
SELECT *
FROM dealsummary

SyntaxError: invalid syntax (<ipython-input-8-fe82fa7d2053>, line 2)

Creating view that shows # deals and value for each deal type

In [3]:
%%sql 
SELECT *
FROM dealsbytype

6 rows affected.

[('C/S', 80, Decimal('271794.0000')),
 ('CM', 3, Decimal('8030.0000')),
 ('PA', 1, Decimal('1880.0000')),
 ('PF', 4, Decimal('27790.0000')),
 ('SS', 59, Decimal('204658.0000')),
 ('TO', 16, Decimal('55972.0000'))]

Create a Summary view for firms showing # deals and value per firm

In [4]:
%%sql 
SELECT *
FROM dealsbyfirm

257 rows affected.

[(2, 6, Decimal('84480.0000')),
 (3, 1, Decimal('1000.0000')),
 (11, 4, Decimal('81202.0000')),
 (12, 1, Decimal('1000.0000')),
 (19, 4, Decimal('4950.0000')),
 (33, 4, Decimal('79960.0000')),
 (36, 1, Decimal('1870.0000')),
 (41, 1, Decimal('1000.0000')),
 (42, 1, Decimal('1000.0000')),
 (46, 2, Decimal('3900.0000')),
 (50, 2, Decimal('19500.0000')),
 (62, 1, Decimal('12000.0000')),
 (64, 1, Decimal('1080.0000')),
 (65, 1, Decimal('1230.0000')),
 (66, 27, Decimal('151823.0000')),
 (67, 42, Decimal('208889.0000')),
 (68, 57, Decimal('234340.0000')),
 (69, 1, Decimal('5600.0000')),
 (70, 5, Decimal('22530.0000')),
 (71, 31, Decimal('168131.0000')),
 (72, 2, Decimal('2850.0000')),
 (73, 12, Decimal('23230.0000')),
 (74, 1, Decimal('1120.0000')),
 (75, 2, Decimal('3600.0000')),
 (76, 43, Decimal('240471.0000')),
 (77, 10, Decimal('25923.0000')),
 (78, 12, Decimal('49488.0000')),
 (79, 11, Decimal('34183.0000')),
 (80, 23, Decimal('148940.0000')),
 (81, 20, Decimal('191227.0000')),
 (82, 2, Decimal('3117.0000')),
 (83, 1, Decimal('1617.0000')),
 (84, 1, Decimal('1617.0000')),
 (85, 2, Decimal('3117.0000')),
 (86, 1, Decimal('1360.0000')),
 (87, 47, Decimal('159730.0000')),
 (88, 6, Decimal('13717.0000')),
 (89, 6, Decimal('13293.0000')),
 (90, 2, Decimal('2860.0000')),
 (91, 40, Decimal('238901.0000')),
 (92, 3, Decimal('4050.0000')),
 (93, 3, Decimal('19510.0000')),
 (94, 5, Decimal('89660.0000')),
 (95, 5, Decimal('91380.0000')),
 (96, 3, Decimal('6439.0000')),
 (97, 1, Decimal('7000.0000')),
 (98, 5, Decimal('16950.0000')),
 (99, 16, Decimal('48079.0000')),
 (100, 6, Decimal('20870.0000')),
 (101, 1, Decimal('6590.0000')),
 (102, 1, Decimal('1700.0000')),
 (103, 1, Decimal('1100.0000')),
 (104, 1, Decimal('1100.0000')),
 (106, 1, Decimal('1355.0000')),
 (107, 1, Decimal('1355.0000')),
 (108, 1, Decimal('1900.0000')),
 (109, 3, Decimal('4200.0000')),
 (110, 7, Decimal('18747.0000')),
 (112, 2, Decimal('2625.0000')),
 (113, 27, Decimal('82524.0000')),
 (114, 2, Decimal('2625.0000')),
 (116, 32, Decimal('128135.0000')),
 (119, 4, Decimal('6405.0000')),
 (120, 31, Decimal('260494.0000')),
 (121, 2, Decimal('19500.0000')),
 (122, 1, Decimal('1200.0000')),
 (123, 1, Decimal('1500.0000')),
 (124, 3, Decimal('4150.0000')),
 (125, 2, Decimal('4220.0000')),
 (126, 1, Decimal('2820.0000')),
 (127, 1, Decimal('1000.0000')),
 (128, 6, Decimal('25480.0000')),
 (129, 6, Decimal('6440.0000')),
 (130, 2, Decimal('2000.0000')),
 (132, 1, Decimal('2223.0000')),
 (133, 1, Decimal('2223.0000')),
 (136, 1, Decimal('1000.0000')),
 (137, 6, Decimal('82880.0000')),
 (138, 1, Decimal('2000.0000')),
 (139, 1, Decimal('2000.0000')),
 (140, 1, Decimal('1100.0000')),
 (141, 1, Decimal('1080.0000')),
 (142, 1, Decimal('1080.0000')),
 (143, 2, Decimal('2500.0000')),
 (144, 5, Decimal('7280.0000')),
 (145, 3, Decimal('16100.0000')),
 (146, 1, Decimal('1500.0000')),
 (147, 1, Decimal('9000.0000')),
 (148, 1, Decimal('9000.0000')),
 (149, 5, Decimal('12670.0000')),
 (150, 2, Decimal('11000.0000')),
 (151, 10, Decimal('22309.0000')),
 (152, 1, Decimal('1180.0000')),
 (153, 1, Decimal('1180.0000')),
 (154, 4, Decimal('7740.0000')),
 (155, 1, Decimal('2800.0000')),
 (156, 4, Decimal('8747.0000')),
 (157, 21, Decimal('131547.0000')),
 (160, 2, Decimal('8100.0000')),
 (161, 2, Decimal('26180.0000')),
 (164, 1, Decimal('1200.0000')),
 (173, 2, Decimal('2140.0000')),
 (177, 1, Decimal('2223.0000')),
 (188, 3, Decimal('6940.0000')),
 (190, 1, Decimal('1100.0000')),
 (196, 2, Decimal('2600.0000')),
 (197, 2, Decimal('6650.0000')),
 (199, 3, Decimal('10500.0000')),
 (200, 2, Decimal('4900.0000')),
 (204, 2, Decimal('3300.0000')),
 (205, 1, Decimal('1000.0000')),
 (207, 2, Decimal('6490.0000')),
 (210, 1, Decimal('1800.0000')),
 (215, 1, Decimal('1250.0000')),
 (217, 2, Decimal('2850.0000')),
 (219, 1, Decimal('1200.0000')),
 (220, 1, Decimal('1500.0000')),
 (222, 13, Decimal('66460.0000')),
 (225, 5, Decimal('9500.0000')),
 (227, 4, Decimal('10470.0000')),
 (228, 2, Decimal('2600.0000')),
 (229, 1, Decimal('1617.0000')),
 (234, 29, Decimal('101062.0000')),
 (236, 1, Decimal('1150.0000')),
 (237, 4, Decimal('8490.0000')),
 (238, 3, Decimal('5910.0000')),
 (239, 13, Decimal('41785.0000')),
 (240, 1, Decimal('1870.0000')),
 (243, 1, Decimal('1075.0000')),
 (244, 1, Decimal('1300.0000')),
 (246, 2, Decimal('3300.0000')),
 (247, 2, Decimal('4720.0000')),
 (248, 63, Decimal('259318.0000')),
 (249, 4, Decimal('8500.0000')),
 (251, 1, Decimal('1300.0000')),
 (257, 3, Decimal('6530.0000')),
 (258, 2, Decimal('15000.0000')),
 (259, 12, Decimal('120660.0000')),
 (260, 18, Decimal('121480.0000')),
 (261, 1, Decimal('1050.0000')),
 (263, 52, Decimal('165661.0000')),
 (265, 5, Decimal('26182.0000')),
 (266, 27, Decimal('156500.0000')),
 (268, 21, Decimal('80788.0000')),
 (269, 3, Decimal('3000.0000')),
 (272, 2, Decimal('5100.0000')),
 (273, 4, Decimal('5129.0000')),
 (274, 1, Decimal('2322.0000')),
 (283, 19, Decimal('136587.0000')),
 (284, 1, Decimal('8000.0000')),
 (287, 15, Decimal('34331.0000')),
 (291, 3, Decimal('4140.0000')),
 (293, 6, Decimal('19373.0000')),
 (294, 1, Decimal('1617.0000')),
 (295, 8, Decimal('23164.0000')),
 (297, 1, Decimal('1800.0000')),
 (301, 1, Decimal('1100.0000')),
 (302, 1, Decimal('1617.0000')),
 (303, 1, Decimal('1600.0000')),
 (304, 1, Decimal('2820.0000')),
 (306, 9, Decimal('116080.0000')),
 (308, 1, Decimal('1590.0000')),
 (309, 2, Decimal('3900.0000')),
 (310, 1, Decimal('1180.0000')),
 (311, 1, Decimal('2900.0000')),
 (312, 1, Decimal('1500.0000')),
 (314, 2, Decimal('2383.0000')),
 (316, 2, Decimal('4610.0000')),
 (319, 1, Decimal('5600.0000')),
 (320, 1, Decimal('3700.0000')),
 (321, 3, Decimal('9140.0000')),
 (325, 1, Decimal('1600.0000')),
 (326, 30, Decimal('95958.0000')),
 (327, 2, Decimal('3000.0000')),
 (330, 1, Decimal('3000.0000')),
 (333, 1, Decimal('1650.0000')),
 (339, 3, Decimal('18800.0000')),
 (342, 14, Decimal('131470.0000')),
 (345, 25, Decimal('197217.0000')),
 (346, 1, Decimal('1500.0000')),
 (347, 1, Decimal('2000.0000')),
 (357, 26, Decimal('161219.0000')),
 (361, 28, Decimal('206087.0000')),
 (364, 2, Decimal('3200.0000')),
 (365, 9, Decimal('47740.0000')),
 (366, 1, Decimal('1180.0000')),
 (367, 10, Decimal('22087.0000')),
 (368, 1, Decimal('1500.0000')),
 (370, 1, Decimal('9700.0000')),
 (371, 2, Decimal('5000.0000')),
 (372, 1, Decimal('1150.0000')),
 (373, 4, Decimal('16723.0000')),
 (374, 1, Decimal('1900.0000')),
 (375, 2, Decimal('5200.0000')),
 (376, 2, Decimal('3000.0000')),
 (377, 1, Decimal('1700.0000')),
 (378, 1, Decimal('1700.0000')),
 (379, 1, Decimal('1057.0000')),
 (380, 3, Decimal('5100.0000')),
 (381, 1, Decimal('2900.0000')),
 (382, 11, Decimal('56887.0000')),
 (383, 2, Decimal('4110.0000')),
 (384, 1, Decimal('1230.0000')),
 (385, 1, Decimal('1230.0000')),
 (386, 3, Decimal('11213.0000')),
 (387, 1, Decimal('8180.0000')),
 (388, 2, Decimal('3030.0000')),
 (389, 1, Decimal('1100.0000')),
 (391, 2, Decimal('3900.0000')),
 (453, 1, Decimal('2350.0000')),
 (454, 1, Decimal('1197.0000')),
 (459, 8, Decimal('19560.0000')),
 (460, 1, Decimal('3000.0000')),
 (464, 2, Decimal('19500.0000')),
 (465, 1, Decimal('1000.0000')),
 (468, 1, Decimal('6200.0000')),
 (469, 1, Decimal('2560.0000')),
 (470, 1, Decimal('1490.0000')),
 (473, 1, Decimal('6200.0000')),
 (475, 1, Decimal('1000.0000')),
 (477, 1, Decimal('1250.0000')),
 (478, 1, Decimal('1150.0000')),
 (479, 3, Decimal('7500.0000')),
 (480, 1, Decimal('1100.0000')),
 (481, 1, Decimal('6200.0000')),
 (484, 1, Decimal('2500.0000')),
 (487, 1, Decimal('2600.0000')),
 (488, 2, Decimal('2625.0000')),
 (489, 2, Decimal('2814.0000')),
 (490, 2, Decimal('5700.0000')),
 (491, 3, Decimal('78880.0000')),
 (492, 1, Decimal('1800.0000')),
 (494, 1, Decimal('2600.0000')),
 (499, 1, Decimal('2300.0000')),
 (500, 1, Decimal('1300.0000')),
 (501, 1, Decimal('2600.0000')),
 (502, 6, Decimal('89200.0000')),
 (503, 1, Decimal('1392.0000')),
 (504, 1, Decimal('1920.0000')),
 (505, 1, Decimal('6200.0000')),
 (506, 1, Decimal('1880.0000')),
 (507, 1, Decimal('1880.0000')),
 (508, 1, Decimal('1880.0000')),
 (509, 1, Decimal('1200.0000')),
 (510, 1, Decimal('1600.0000')),
 (511, 1, Decimal('1600.0000')),
 (512, 2, Decimal('10060.0000')),
 (513, 1, Decimal('1050.0000')),
 (514, 1, Decimal('6800.0000')),
 (515, 1, Decimal('6800.0000')),
 (516, 1, Decimal('1330.0000')),
 (517, 1, Decimal('1100.0000')),
 (518, 1, Decimal('1100.0000')),
 (519, 1, Decimal('1000.0000')),
 (520, 1, Decimal('1000.0000')),
 (521, 1, Decimal('2000.0000')),
 (522, 1, Decimal('1283.0000'))]

Creating view that shows Company names and roles

In [ ]:
%%sql 
SELECT *
FROM dealsplayers